LobbySignPrefix: "[ug lsign]"
ClickInputSignPrefix: "[ug cisign]"
RedstoneInputSignPrefix: "[ug risign]"
TextOutputSignPrefix: "[ug tosign]"
RedstoneOutputSignPrefix: "[ug rosign]"
enableAPI: true
APIPort: 8080
debug: false